### ISSUE TITLE
Installer doesn't set SAGEPLEX_CFG environment variable.

### ISSUE THREAD

**Issue by CraziFuzzy** [ai7/sagetv-for-plexmediacenter#12]
So I finally got around to updating the plugin (was still using Pix64's latest version). Started from scratch to test the waters completely, used the installer, and it detected my non-standard locations perfectly (Plex is in P:\PlexData\Plex Media Server). It configured the sageplex_cfg.json file fine, but scans would not work. It looks like the installer is not setting the SAGEPLEX_CFG environment variable, which is preventing the scanner from working (just errors out). Took me a while to track this down, and once I set the environment variable to point to the json file in the Plex Media Server folder, things appear to be scanning properly.

**Comment by ai7** [comment]
Good catch. The SAGEPLEX_CFG environment variable is supposed to be optional. The plugin should be able to locate the PMS data folder on its own. If it can't for some reason, you can use the environment variable to set it.

The bug happens because the installer actually contains more logic in locating the PMS data folder than the plugin. I think the plugin should at least be as smart as the installer so you don't need to deal with the SAGEPLEX_CFG environment variable. Will fix this.

**Comment by ai7** [comment]
It turns out the PMS plugin environment doesn't support the _wreg module for accessing the registry due to their sandboxed environment for running the plugin. 

So I updated the installer to set the SAGEPLEX_CFG environment variable during install. This should address the issue.

commit 0c40e40
